//! Symmetric algebra S(V) as a superalgebra.

use crate::graded::{GradedElement, Parity};
use serde::{Deserialize, Serialize};

/// Symmetric algebra: quotient of tensor algebra by the ideal generated by v⊗w - w⊗v.
/// For the super version, we use the super-symmetric ideal:
/// v⊗w - (-1)^|v||w| w⊗v.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SymmetricAlgebra {
    pub n_generators: usize,
    pub generator_parities: Vec<Parity>,
    pub labels: Vec<String>,
}

impl SymmetricAlgebra {
    pub fn new(parities: Vec<Parity>, labels: Vec<String>) -> Self {
        let n = parities.len();
        let labels = if labels.len() == n { labels } else {
            (0..n).map(|i| format!("x{}", i)).collect()
        };
        SymmetricAlgebra { n_generators: n, generator_parities: parities, labels }
    }

    /// The symmetric product of generators i and j.
    /// For bosonic (even) generators: commutative, xy = yx.
    /// For fermionic (odd) generators: anticommutative (super symmetric), θη = -ηθ.
    pub fn sym_product(&self, i: usize, j: usize) -> (f64, Parity) {
        let pi = self.generator_parities[i];
        let pj = self.generator_parities[j];
        let result_parity = pi.combine(pj);
        // If both odd, the super-symmetric product is antisymmetric: θ⊗θ = 0
        if i == j && pi == Parity::Odd {
            (0.0, result_parity)
        } else {
            (1.0, result_parity)
        }
    }

    /// Check supercommutativity: ab = (-1)^|a||b| ba.
    pub fn is_supercommutative(&self) -> bool {
        for i in 0..self.n_generators {
            for j in 0..self.n_generators {
                let (v_ij, _) = self.sym_product(i, j);
                let (v_ji, _) = self.sym_product(j, i);
                let sign = if !(self.generator_parities[i].grade() * self.generator_parities[j].grade()).is_multiple_of(2) { -1.0 } else { 1.0 };
                if (v_ij - sign * v_ji).abs() > 1e-10 {
                    return false;
                }
            }
        }
        true
    }

    /// Generators as graded elements.
    pub fn generators_as_graded(&self) -> Vec<GradedElement> {
        self.labels.iter().enumerate().map(|(i, l)| {
            GradedElement { value: 1.0, parity: self.generator_parities[i], label: l.clone() }
        }).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_symmetric_bosonic_commutative() {
        let s = SymmetricAlgebra::new(
            vec![Parity::Even, Parity::Even],
            vec!["x".into(), "y".into()],
        );
        let (xy, _) = s.sym_product(0, 1);
        let (yx, _) = s.sym_product(1, 0);
        assert!((xy - yx).abs() < 1e-10);
    }

    #[test]
    fn test_symmetric_fermionic_nilpotent() {
        let s = SymmetricAlgebra::new(
            vec![Parity::Odd],
            vec!["θ".into()],
        );
        let (v, _) = s.sym_product(0, 0);
        assert!(v.abs() < 1e-10);
    }

    #[test]
    fn test_symmetric_supercommutative() {
        let s = SymmetricAlgebra::new(
            vec![Parity::Even, Parity::Odd],
            vec!["x".into(), "θ".into()],
        );
        assert!(s.is_supercommutative());
    }
}
